import { Inter } from "next/font/google";
import "./globals.css";
import ThemeSwitcher from "./components/ThemeSwitcher";
import Link from "next/link";
import Provider from "./provider";
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
              <header className="py-6">
                <div className="container flex items-center justify-between">
                  <ul>
                    <li>
                      <Link href="/">Home</Link>
                    </li>
                  </ul>
                </div>
            </header>
        <Provider>
            <main>
            {children}
            </main>
        </Provider>
      </body>
    </html>
  );
}
